### ISSUE TITLE
It's not supported in latest version of Defold (1.9.3)

### ISSUE THREAD

**Issue by bdshahab** [subsoap/defos#140]
Please fix the problem as soon as possible and release the new version.

**Comment by britzl** [comment]
What happens? Is it crashing? Is some specific function not working? Are you not able to build your project using Defold 1.9.3 and latest DefOS?

**Comment by bdshahab** [comment]
It cannot be run and cannot install its dependency!

/defos/ext.manifest
	An error occurred while building Native Extensions, but the server provided no information.

**Comment by britzl** [comment]
I am using Defold 1.9.3 and was able to build a project with DefOS added as a dependency. I tested with macOS, Windows, Android and HTML5.

> It cannot be run and cannot install its dependency!
> 
> /defos/ext.manifest An error occurred while building Native Extensions, but the server provided no information.

Which version of Defold are you using? Which platform are you building for?

**Comment by bdshahab** [comment]
https://github.com/britzl/defold-clipboard/issues/9#issuecomment-2376002072

**Comment by Morgerion** [comment]
I too am using DefOS on the latest version of Defold (1.9.3) and all functionality works.

**Comment by bdshahab** [comment]
This problem is not for you!
It is for Iranians (and other countries sanctioned by Google)!

**Comment by britzl** [comment]
> This problem is not for you! It is for Iranians (and other countries sanctioned by Google)!

The problem is unfortunately out of our hands. You could set up a local build server and not use the one hosted on GCP or try accessing the build server via a VPN if that is possible.
