### ISSUE TITLE
Extra Windows 10 window features

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#25]
![1](https://cloud.githubusercontent.com/assets/409170/26432394/5c5b80b6-40b0-11e7-90c2-b3ee88c3e81f.png)

![2](https://cloud.githubusercontent.com/assets/409170/26432406/7323baca-40b0-11e7-967d-7b6c2b30a092.png)

**Comment by chaosddp** [comment]
as i know this is UAP(win8.1) feature, win32 apps do not have this kind of titlebar, now UWP apps on win10 do not have the first menu in first picture by default, but the titlebar can be extend.

**Comment by subsoap** [comment]
I see. Solution is to get Defold team to build Windows target for UAP!

**Comment by chaosddp** [comment]
Yes, but since Windows 10 is latest build, i think UWP is more reasonable to be supported, then we can write an extension to add menu in titlebar.

**Comment by subsoap** [comment]
Closing. Can support UWP if Defold team ever makes a target for it.
