### ISSUE TITLE
Maximize issue on Windows

### ISSUE THREAD

**Issue by britzl** [subsoap/defos#27]
Reported by forum user Ross Grams:

I still have a weird issue with maximizing. I think I’ve narrowed it down—if, before toggling maximized or fullscreen from DefOS, I use the windows command (windows-button + up) to maximize the window, then toggle maximize from DefOS, the window vanishes completely. It doesn’t show up in the task bar or the task manager, but it’s still running and sending stuff to the editor console. The only way to stop it is to kill the dmengine.exe process from the task manager (or build from the editor again).

If I do Win+Up to maximize, then toggle fullscreen from DefOS, then toggle maximized or fullscreen back again from DefOS, it crashes.

**Comment by subsoap** [comment]
>If I do Win+Up to maximize, then toggle fullscreen from DefOS, then toggle maximized or fullscreen back again from DefOS, it crashes.

Just tested and this still is an issue.

**Comment by dapetcu21** [comment]
This seems fixed. Re-open if it's not
