### ISSUE TITLE
Sometimes defos.toggle_fullscreen() makes the game close on Windows

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#30]
I have yet to find the cause

**Comment by subsoap** [comment]
It seems to always be going from Window Mode to Fullscreen so there may be some problem there.

**Comment by chaosddp** [comment]
i just take a look at the toggle_fullscreen source code, there is a branch (line 155 in defos_win.c) to set the window size to (0, 0, 0, 0),  seems like the root cause?

**Comment by subsoap** [comment]
Seems like possible cause!
