### ISSUE TITLE
Show/hide output console

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#35]
https://forum.defold.com/t/windows-release-build-with-native-extensions-eta/13477/6

https://docs.microsoft.com/en-us/windows/console/freeconsole
http://www.cplusplus.com/forum/beginner/12001/

**Comment by subsoap** [comment]
```
#include <Windows.h>

void HideConsole()
{
    ::ShowWindow(::GetConsoleWindow(), SW_HIDE);
}

void ShowConsole()
{
    ::ShowWindow(::GetConsoleWindow(), SW_SHOW);
}

bool IsConsoleVisible()
{
    return (::IsWindowVisible(::GetConsoleWindow()) != FALSE);
}
```

**Comment by subsoap** [comment]
Working test in https://github.com/subsoap/defos/tree/toggle_debug_console

@chaosddp Could you test this too?

@AGulev If you build debug on Mac does a console similar to this appear or is this only a Windows thing?

**Comment by subsoap** [comment]
BTW, only works on Windows and only with bundled builds not in editor builds as far as I can tell.

**Comment by AGulev** [comment]
Hard week, I'll back to this issue after next week

**Comment by subsoap** [comment]
Maybe add set_console_title since the default title is just the path to the exe

https://docs.microsoft.com/en-us/windows/console/setconsoletitle

**Comment by chaosddp** [comment]
@subsoap work fine on my Windows, and is it necessary to change title as it usually used for debug?
Also do not forget to share us the link of your game after release :)

**Comment by subsoap** [comment]
@chaosddp will for sure and send you Steam keys!

Allowing changing the title I think would still be useful because the window title can be used to update things over time without filling up the console with prints such as FPS, server heartbeat, uptime. Some users may use it for showing server related info too.

**Comment by AGulev** [comment]
@subsoap I have no console on mac

**Comment by AGulev** [comment]
@subsoap Do you have plans to merge console methods into master?

**Comment by subsoap** [comment]
@AGulev Should it be included in DefOS since it's Windows only and a minor thing for Windows debug builds? Maybe better as its own small NE.

**Comment by subsoap** [comment]
@AGulev I'll deal with it soon.
