### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#37]
Native extensions now supports Linux so support for it needs to be added.

**Comment by chaosddp** [comment]
I am not familar about Linux, is it easy to add support, as there are different UI system?
Such as maximize window, or change the title.

**Comment by subsoap** [comment]
Not sure, but it should be possible to do everything we want it to do. Can look at how GLFW does everything for Linux. Have to wait until Editor 2 adds support for building/bundling before I can begin.

**Comment by subsoap** [comment]
I really want to work on this soon. I'll make dummy functions first then fill in what works.

**Comment by dapetcu21** [comment]
I’ll surely pick it up when our game gets close to release if nobody else does before me, as we intend to release on Linux as well. But there are things with more priority in development, and I’d prefer to focus on getting the game done before we port it.

**Comment by chaosddp** [comment]
Working in #70, and need help!

**Comment by chaosddp** [comment]
List missing features for Linux that i cannot find a resolution here:

defos_set_cursor_locked
defos_is_cursor_locked
defos_is_cursor_clipped
defos_set_cursor_clipped
defos_set_cursor_visible
defos_disable_window_resize
defos_disable_minimize_button
defos_disable_maximize_button
defos_is_mouse_in_view
