### ISSUE TITLE
API change proposal

### ISSUE THREAD

**Issue by dapetcu21** [subsoap/defos#50]
I propose we change the following:

```lua
defos.disable_mouse_cursor()
defos.enable_mouse_cursor()
defos.toggle_maximize()
defos.is_maximized()
defos.toggle_fullscreen()
defos.is_fullscreen()
```

To the following:

```lua
defos.set_mouse_cursor_hidden(true)
defos.set_mouse_cursor_hidden(false)
defos.is_mouse_cursor_hidden()
defos.set_maximized(true)
defos.set_maximized(false)
defos.is_maximized()
defos.set_fullscreen(true)
defos.set_fullscreen(false)
defos.is_fullscreen()
```

This has the benefit of not having to know what state fullscreen is in before you toggle. You can just say `set_fullscreen(true)` to make sure you're in full screen, and if you were already full screen, then nothing happens. Toggle could be implemented by the user as `defos.set_fullscreen(not defos.is_fullscreen())`.

What do you think?

This is obviously a breaking change, but better make it now before 1.0.

**Comment by chaosddp** [comment]
good idea, and how about make them shorter? like

```
defos.set_cursor_hidden(true)
defos.set_cursor_hidden(false)
```

**Comment by subsoap** [comment]
Should make a 1.0 release first (can be done now) and then yes API changes can be done.

**Comment by dapetcu21** [comment]
@subsoap @chaosddp You can delete tags. I just deleted the extra one.
```bash
git tag -d 1.0.0
git push upstream :refs/tags/1.0.0
```

**Comment by subsoap** [comment]
Can change these that are left if you still want to before 2.0 otherwise please close.

**Comment by dapetcu21** [comment]
I changed them in #61. I'd like to also try to implement cursor clipping on macOS before 2.0. Would that be ok with you?

**Comment by subsoap** [comment]
Yes.

**Comment by dapetcu21** [comment]
@subsoap Done 😄
