### ISSUE TITLE
Proposal: move_mouse_to

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#53]
```defos.move_mouse_to(x,y)```

Move mouse to x,y coordinates of the game window client area.

win/mac/linux only

**Comment by chaosddp** [comment]
[this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648394(v=vs.85).aspx) is the function to set mouse position for win, i can have a try tonight after work.

**Comment by AGulev** [comment]
solution [for mac](https://stackoverflow.com/questions/12995522/programmatically-control-a-mac-cursor-in-objective-c)

**Comment by chaosddp** [comment]
Done at #57
