### ISSUE TITLE
Alt+f4 and Alt+enter on windows

### ISSUE THREAD

**Issue by AGulev** [subsoap/defos#59]
I am working with publisher and we make Win version of the game.
He told that Alt+f4 and Alt+enter - "must have" functions on windows.

I tried to make this function in lua, but in some popups I block message passing 
```
function on_input() 
...
return true
end
```
What do you think, should I add this functions to defos (Win only)? 
Or it should be an optional for a developer? But how this options should work then? Do you have any ideas?

**Comment by dapetcu21** [comment]
You could technically solve this by putting your whole game in a collection proxy, then in your main collection, give input focus to the script doing alt+f4 after giving input focus to your game's collection proxy.

**Comment by AGulev** [comment]
@dapetcu21  
yes, I know, I don't want to make things like this. It's dirty hack, not  solving of the issue.

**Comment by dapetcu21** [comment]
Then again, using defos to do input feels similarly feels like a dirty hack

**Comment by AGulev** [comment]
Defos - is the native os functions
alt+f4 and alt-enter - native behavior on windows. 

Ok, if you think this way, I make it in my local brunch.

**Comment by dapetcu21** [comment]
I don't have a strong opinion about this... Both approaches don't feel right to me and I honestly think that Alt+F4 to quit should have been default Defold behaviour. 

Thinking about it, I think you're right in the sense that defos could provide this event to developers for convenience, even though it's not strictly its job. So maybe we could put it in.

**Comment by subsoap** [comment]
These are what I use for alt+f4 / alt+enter - I also use F11 for toggling fullscreen like browsers do, and esc for closing (esc should open a window to confirm, alt+f4 should close directly).

```
function init(self)
	self.alt_held = false
end


function update(self, dt)
	self.alt_held = false	
end

function on_input(self, action_id, action)
	if action_id == input.key_lalt or action_id == input.key_ralt then
		self.alt_held = true
	end
	
	if (action_id == input.key_f4 and self.alt_held == true) or action_id == input.key_esc then
		msg.post("@system:", "exit", {code = 0})
	end

	if (action_id == input.key_f11 and action.released) or (action_id == input.key_enter and self.alt_held == true) then
		defos.toggle_fullscreen()
	end
end
```
