### ISSUE TITLE
Add ability to make window maximized

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#6]
Should be this with SW_SHOWMAXIMIZED I think
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx

Could also add functions for minimizing, making window get focus, making taskbar blink / light up,

**Comment by AGulev** [comment]
I can make almost the same things on macOS, but I think we have to get most important and frequency used things and implement them.

**Comment by AGulev** [comment]
something like function 
defos.set_window_mode(param)
and parameters
defos.SHOW_MAXIMIZED
defos.SHOW_FULLSCREEN
defos.SHOW_WINDOWED
or something like this.

I am not sure about case of using : window get focus, making taskbar blink / light up,

**Comment by subsoap** [comment]
WIP version going to add it in properly later

```
local M = {}

local ffi = package.preload.ffi()


function M.maximize_window()
	if(ffi.os == "Windows") then

	  -- definitions
	  ffi.cdef([[
			typedef unsigned int LONG;
			typedef long long LONG_PTR;
			typedef void* PVOID;
			typedef PVOID HANDLE;
			typedef HANDLE HWND;
			typedef unsigned int UINT;
			typedef bool BOOL;

			HWND GetActiveWindow();
			BOOL ShowWindow(HWND hWnd, int nCmdShow);
			
		]])

		-- load User32.dll
		local user32 = ffi.load("User32")

		local SW_SHOWMAXIMIZED = 3
		
		
		local ptr = user32.GetActiveWindow()
		
		user32.ShowWindow(ptr, SW_SHOWMAXIMIZED)
		
	end	
end	

return M
```

**Comment by AGulev** [comment]
Fully agree with you about version 1.0 and 2.0 .
And thanks for the maximize option ( option key + shift + green button) I never known about it =)))

**Comment by AGulev** [comment]
As I undestand this issue is done?
new methods:
defos.toggle_maximize()
and
defos.is_maximize()
was added
