### ISSUE TITLE
defos.set_cursor_locked behaves badly on windows

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#80]
It should not be allowed to change cursor position when window is not in focus

**Comment by subsoap** [comment]
Same with defos.move_cursor_to

**Comment by dapetcu21** [comment]
I'm pretty sure it's bad UX to lock the user's cursor when your app is not in focus...

**Comment by subsoap** [comment]
Yes, I'm saying the current DefOS behavior is bad and needs to not change cursor position when game does not have focus as it currently does.

**Comment by dapetcu21** [comment]
Oh, fair. You're right

**Comment by subsoap** [comment]
Defold devs can of course use window.set_listener to detect when game has focus or not, but I don't think we should give people the option to change mouse position when window is not in focus as the uses for it are more nefarious than legitimate.

**Comment by dapetcu21** [comment]
Not to mention, many people might just not think this as a problem
