### ISSUE TITLE
Keep window always on top

### ISSUE THREAD

**Issue by Gianmichele** [subsoap/defos#83]
I use defos on a day to day basis to change resolution on the fly and test against the most common mobile ones and it is great!
It would be also great to have an option to always keep the window on top of the others. I use hot reload a lot and that would help not switch windows constantly.

**Comment by subsoap** [comment]
Should be easy to add 

https://stackoverflow.com/a/31170225

**Comment by subsoap** [comment]
BTW if you need this sooner you can download DefOS and modify the set window position function to have the flag enabled by default and then use that version while you are developing.
