### ISSUE TITLE
Option to scale cursor on Linux for high dpi screens?

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#96]
![2019-03-20 16_27_50-messages_ messages](https://user-images.githubusercontent.com/409170/54725651-23ef2f00-4b2d-11e9-9dc5-32d2e4cc56d2.png)

**Comment by dapetcu21** [comment]
Fixed in v2.2.1. Just use two pngs in the `xcreatecursor` config, one at size 24 and the 2x one at size 48 (the actual pixel size can be whatever. 24/48 is just the cursor font size (the first column in the config)).

Example:

```
48 19 19 cursor@2x.png 100
24 10 9 cursor.png 100
```
